import { Inter } from "next/font/google";
import "./globals.css"; // 他の全体のスタイル
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* サイドバーは各ページで管理するため、ここでは表示しない */}
        {children}
      </body>
    </html>
  );
}
